const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');
const os = require('os');

const app = express();
const PORT = 3000;
const DB_DIR = path.join(__dirname, 'db');
const DB_FILE = path.join(DB_DIR, 'visits.json');

// Middleware
app.use(cors());
app.use(bodyParser.json({ limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Ensure DB exists
if (!fs.existsSync(DB_DIR)) {
    fs.mkdirSync(DB_DIR, { recursive: true });
}
if (!fs.existsSync(DB_FILE)) {
    fs.writeFileSync(DB_FILE, '[]');
}

// Helper: Get IP
function getLocalIP() {
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            if (iface.family === 'IPv4' && !iface.internal) {
                return iface.address;
            }
        }
    }
    return '127.0.0.1';
}

const nodemailer = require('nodemailer');

// ... (existing imports)

// EMAIL CONFIGURATION
// Ideally, use environment variables. For now, we need user input for credentials.
// Or use a local SMTP? Let's setup a transporter but wrap in try-catch.
const transporter = nodemailer.createTransport({
    service: 'gmail', // Standard for small businesses
    auth: {
        user: 'Boxnfly@gmail.com', // User's email from previous context
        pass: 'YOUR_APP_PASSWORD_HERE' // User needs to provide this!
    }
});

const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

// SUPABASE CONFIGURATION
const supabaseUrl = process.env.SUPABASE_URL || 'https://YOUR_PROJECT.supabase.co';
const supabaseKey = process.env.SUPABASE_KEY || 'YOUR_ANON_KEY';
const supabase = createClient(supabaseUrl, supabaseKey);

app.post('/api/checkin', async (req, res) => {
    try {
        const visit = {
            // id: auto-generated by Supabase
            created_at: new Date().toISOString(),
            name: req.body.name,
            phone: req.body.phone,
            email: req.body.email,
            treatment: req.body.treatment,
            consent_text: req.body.consentText,
            signature: req.body.signature // Ensure schema has text column for this
        };

        // Insert into Supabase
        const { data, error } = await supabase
            .from('visits')
            .insert([visit])
            .select();

        if (error) throw error;

        console.log(`✅ [${new Date().toLocaleTimeString()}] Check-in: ${visit.name}`);

        // SEND EMAIL (If configured)
        if (visit.email && visit.email.includes('@') && process.env.EMAIL_USER) {
            const mailOptions = {
                from: '"Studio Luna" <Boxnfly@gmail.com>',
                to: visit.email,
                subject: `Your Consent Form - ${visit.treatment}`,
                html: `
                    <div style="font-family: Arial, sans-serif; color: #333;">
                        <h2 style="color: #D4AF37;">Studio Luna Body Sculpting</h2>
                        <p>Hi ${visit.name},</p>
                        <p>Thank you for checking in for your <strong>${visit.treatment}</strong> today.</p>
                        <p>Attached below is a copy of the consent form needed for your records.</p>
                        
                        <div style="background: #f9f9f9; padding: 15px; border-left: 4px solid #D4AF37; margin: 20px 0;">
                            <strong>Consent Agreement:</strong><br/>
                            <em style="font-size: 13px; color: #555;">${visit.consent_text}</em>
                        </div>

                        <p>Your signature was recorded at ${new Date().toLocaleString()}.</p>
                        
                        <p style="margin-top: 30px; font-size: 12px; color: #888;">
                            Studio Luna Body Sculpting<br/>
                            (555) 123-4567 | www.studioluna.com
                        </p>
                    </div>
                `,
                attachments: [
                    {
                        filename: 'signature.png',
                        content: visit.signature.split('base64,')[1],
                        encoding: 'base64'
                    }
                ]
            };

            /* EMAIL DISABLED PENDING APP PASSWORD
            transporter.sendMail(mailOptions, (error, info) => {
                if (error) {
                    console.log('Error sending email:', error);
                } else {
                    console.log('Email sent: ' + info.response);
                }
            });
            */
            console.log("Create App Password in server.js to enable emails.");
        }

        res.json({ success: true, id: data[0]?.id });
    } catch (e) {
        console.error("Error saving check-in:", e);
        res.status(500).json({ error: e.message });
    }
});

// API: List Visits
app.get('/api/visits', async (req, res) => {
    try {
        const { data, error } = await supabase
            .from('visits')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        // Map back to frontend expected format
        const formatted = data.map(v => ({
            id: v.id,
            timestamp: v.created_at,
            name: v.name,
            phone: v.phone,
            email: v.email,
            treatment: v.treatment,
            consentText: v.consent_text,
            signature: v.signature
        }));

        res.json(formatted);
    } catch (e) {
        res.status(500).json({ error: e.message });
    }
});


// Start Server (Local Only)
if (require.main === module) {
    app.listen(PORT, async () => {
        const ip = getLocalIP();
        const url = `http://${ip}:${PORT}`;

        console.log(`\n🏥 Studio Luna Body Sculpting Check-in Server`);
        console.log(`---------------------------------`);
        console.log(`💻 Dashboard: http://localhost:${PORT}/admin.html`);
        console.log(`📱 Check-in:  ${url}`);
        console.log(`---------------------------------`);
        console.warn('⚠️ IMPORTANT: Data is stored in a local JSON file (db/visits.json). This is NOT suitable for production or Vercel deployments as data will be lost on redeployments/serverless function invocations. Consider a proper database for production use.');
        console.log(`\nScan this QR Code to check in:\n`);

        console.log(await QRCode.toString(url, { type: 'terminal', small: true }));
    });
}

// Export for Vercel
module.exports = app;
