-- Run this in your Supabase SQL Editor

create table public.visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  phone text,
  email text,
  treatment text,
  consent_text text,
  signature text -- Base64 string (consider storing large images in Storage if too big, but text is fine for small sigs)
);

-- Enable Row Level Security (RLS) if you want, but for a simple internal tool, you can leave it open or securing via API key is enough for now.
-- If you use the service_role key in server.js, RLS policies won't block you.
